export type RootStackParamList = {
  Register: undefined;
  RegisterMechanic: {garageId: number} | undefined;
  Login: undefined;
  CustomerMain:  undefined;
  EditProfile: {id: number} | undefined;
  OrderGarage: {id: number, handleType: string} | undefined;
  Waiting: undefined;
  FindGarage: {prevScreen: boolean} |undefined;
  GarageDetail: {id: number} | undefined;
  BottomNav: undefined;
  History: undefined;
  HistoryMechanic: undefined;
  HistoryDetail: {id: number} | undefined;
  HistoryDetailMechanic: {id: number} | undefined;
  Chat: undefined;
  ChatHistory: undefined;
  RegisterGarage: undefined;
  MechanicMain: undefined;
  MechanicOrder: {id: number} | undefined;
  CustomerOrder: {id: number} | undefined;
  RegisterOwner: undefined;
  GarageMain: undefined;
  GarageTransaction: {id: number} | undefined;
  ChatHistoryMechanic: undefined;
  GarageEmployee: undefined;
  MechanicEdit: undefined;
  HistoryGarage: undefined;
};
