import { createSlice, PayloadAction } from '@reduxjs/toolkit';

const garageDataSlice = createSlice({
  name: 'garageData',
  initialState: [
    {
      id:1,
      name: 'Bengkel HAN Paint & Body Repair',
      address:'Jalan Simpang Borobudur II/30, Malang, Jawa Timur',
      photoUrl:'https://fastly.4sqi.net/img/general/600x600/kqcisOYA0E_RxnDI_vbPRBl0mpHPrm4GzSS8duldpWU.jpg',
      openHour:'08.00 - 15.00',
      openDay:'Senin - Sabtu',
      site:'-',
      latitude:-7.93581,
      longitude:112.63633,
      speciality:'Mobil',
      rating:4.6,
      total_rating:72,
      isAvailable: false,
    },
    {
      id:2,
      name: 'Karunia Nyata Motor (KNM)',
      address:'Jalan Borobudur Ruko A.Yani 17/B4-5, Blimbing, Malang, Jawa Timur',
      photoUrl:'https://images.autofun.co.id/file1/7d6197ada81840279d68af0785d4f591_678x380.jpg',
      openHour:'07.30 - 17.00',
      openDay:'Senin - Minggu',
      site:'https://karunianyatamotor.business.site/?utm_source=gmb&utm_medium=referral',
      latitude:-7.94142,
      longitude:112.64211,
      speciality:'Motor',
      rating:4.5,
      total_rating:427,
      isAvailable: true,
    },
    {
      id:3,
      name: 'Bengkel Otomotif "Mobil & Sepeda Motor"',
      address:'Jalan KH. Malik, Kedungkandang, Malang',
      photoUrl:'https://lh3.googleusercontent.com/proxy/d2WkPd-J9TOQ5vfgxe7MmElXs6cNhdKfgkZeU6WbT7Gd3f4rEYvRAhh-YJ2tcIHfBUVFyAyE3paL79LXpCmUdeB2CtNGf3_3nQ0b3DjhI02OTqggLEolRgkn0EXcmf4dWEQTbigfkjP_siJ7pBo7P82eA-sqfaLzUhjQFw=s1360-w1360-h1020',
      openHour:'08.00 - 19.00',
      openDay:'Setiap Hari',
      site:'-',
      latitude:-7.99531,
      longitude:112.65059,
      speciality:'Mobil-Motor',
      rating:5,
      total_rating:1,
      isAvailable: true,
    },
    {
      id:4,
      name: 'Bengkel Borobudur',
      address:'Jalan Sudimoro 10a Malang, Malang, Jawa Timur',
      photoUrl:'https://i0.wp.com/caritempat.online/wp-content/uploads/2020/08/bengkel-borobudur.jpg?resize=904%2C550',
      openHour:'08.00 - 16.00',
      openDay:'Senin - Sabtu',
      site:'-',
      latitude:-7.93617,
      longitude:112.62699,
      speciality:'Mobil',
      rating:4.6,
      total_rating:275,
      isAvailable: true,
    },
    {
      id:5,
      name: 'Bengkel Mobil "ipunk motor"',
      address:'Jalan Blimbing Indah Tengah VIII C3/6 Malang, Jawa Timur',
      photoUrl:'https://images.autofun.co.id/file1/7d6197ada81840279d68af0785d4f591_678x380.jpg',
      openHour:'08.00 - 17.00',
      openDay:'Senin - Sabtu',
      site:'-',
      latitude:-7.93718,
      longitude:112.65603,
      speciality:'Mobil',
      rating:5,
      total_rating:20,
      isAvailable: true,
    },
    {
      id:6,
      name: 'Bengkel Panggilan Motor 24 Jam',
      address:'Jalan Raya Cemorokandang 26 Malang, Jawa Timur',
      photoUrl:'https://images.autofun.co.id/file1/a8b369e5cb5045ae9b1a9e3a75949490_678x380.jpg',
      openHour:'24 Jam',
      openDay:'Setiap Hari',
      site:'-',
      latitude:-7.97551,
      longitude:112.67621,
      speciality:'Motor',
      rating:4.4,
      total_rating:27,
      isAvailable: true,
    },
    {
      id:7,
      name: 'Benkel Suhat Motor',
      address:'Jalan Soekarno Hatta 11 Malang, Jawa Timur',
      photoUrl:'https://lh3.googleusercontent.com/p/AF1QipNexNjPPd2lL1BPS7cHW__uBz1vmDBaZX-xsH8C=w1080-h608-p-k-no-v0',
      openHour:'08.00 - 17.00',
      openDay:'Senin - Sabtu',
      site:'https://bengkel-suhat-motor.business.site/',
      latitude:-7.94530,
      longitude:112.61834,
      speciality:'Motor',
      rating:4.6,
      total_rating:464,
      isAvailable: true,
    },
  ],
  reducers: {
    setGarageData: (state, action: PayloadAction<any[]>) => action.payload
  },
})

export const {setGarageData} = garageDataSlice.actions
export default garageDataSlice.reducer
